[[redirects]]
  from = "/"
  to = "/dashboard"
  status = 200

  [[redirects]]
  from = "/*"
  to = "/"
  status = 200

  [[redirects]]
  from = "/cart"
  to = "/"
  status = 200

  [[redirects]]
  from = "/cart"
  to = "/dashboard"
  status = 200

  [[redirects]]
  from = "/login"
  to = "/dashboard"
  status = 200

  [[redirects]]
  from = "/"
  to = "/login"
  status = 200
